spring.application.name=blodconnect

spring.datasource.url=jdbc:postgresql://ep-falling-grass-a16k6sel.ap-southeast-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_0OeLTqUnIXD3
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false


server.port=8080

app.jwt.secret=bloodconnectSecretKeyHereMakeItLongAndRandom123456
app.jwt.expiration=86400000

# Email Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=care.yourapp@gmail.com
spring.mail.password=wnpe ciwc zmti cfrj
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true